#!/usr/bin/env bash

GITSH_DOWNLOAD_URL="https://github.com/thoughtbot/gitsh/releases/download"
PARITY_DOWNLOAD_URL="https://github.com/thoughtbot/parity/archive/refs/tags"
RCM_DOWNLOAD_URL="https://github.com/thoughtbot/rcm/archive/refs/tags"

release_update() {
  pushd $PACKAGE
  current_version=`dpkg-parsechangelog --show-field Version | cut -d'-' -f1`

  if [ $current_version = $VERSION ]; then
    dch -R "New upstream release ${VERSION}"
  else
    dch -v "${VERSION}-1" -U "New upstream release ${VERSION}"
  fi
  dch -r "" -D stable

  git commit -am "Release $PACKAGE v$VERSION"
  popd
}

release_build() {
  mkdir -p deb-build
  wget -O deb-build/${PACKAGE}_${VERSION}.orig.tar.gz  "$(download_url)"
  tar -C deb-build -xf deb-build/${PACKAGE}_${VERSION}.orig.tar.gz
  cp ${PACKAGE}/debian deb-build/${PACKAGE}-${VERSION} -r
  pushd deb-build/${PACKAGE}-${VERSION}
  debuild -F
  popd
}

release_push() {
  git push
}

release_clean() {
  rm -rf deb-build
}

release_reset() {
  release_clean
  git reset --hard origin/master
}

release_upload() {
  scp deb-build/${PACKAGE}_${VERSION}-?_all.deb thoughtbotapt:.
}

release_sandbox() {
  git fetch
  git checkout -B release-$PACKAGE origin/master
}

release_package() {
  release_sandbox
  release_clean
  release_update
  release_build
  release_upload
}

release_check() {
  uscan --no-download
}

download_url() {
  case $PACKAGE in
    "rcm"*)
      echo "$RCM_DOWNLOAD_URL/v$VERSION.tar.gz"
      ;;
    "parity"*)
      echo "$PARITY_DOWNLOAD_URL/v$VERSION.tar.gz"
      ;;
    "gitsh"*)
      echo "$GITSH_DOWNLOAD_URL/v$VERSION/gitsh-$VERSION.tar.gz"
      ;;
  esac
}

verb="$1"
PACKAGE="$2"
VERSION="$3"
cmd="release_${verb}"

set -x

${cmd}
